//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class destinations {
    
    private destinationsDestination[] destinationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("destination")]
    public destinationsDestination[] destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestination {
    
    private destinationsDestinationHistory historyField;
    
    private destinationsDestinationIntroductory introductoryField;
    
    private destinationsDestinationPractical_information practical_informationField;
    
    private destinationsDestinationTransport transportField;
    
    private destinationsDestinationWeather weatherField;
    
    private destinationsDestinationWildlife wildlifeField;
    
    private destinationsDestinationWork_live_study work_live_studyField;
    
    private uint atlas_idField;
    
    private string asset_idField;
    
    private string titleField;
    
    private string titleasciiField;
    
    /// <remarks/>
    public destinationsDestinationHistory history {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationIntroductory introductory {
        get {
            return this.introductoryField;
        }
        set {
            this.introductoryField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationPractical_information practical_information {
        get {
            return this.practical_informationField;
        }
        set {
            this.practical_informationField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationTransport transport {
        get {
            return this.transportField;
        }
        set {
            this.transportField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWeather weather {
        get {
            return this.weatherField;
        }
        set {
            this.weatherField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWildlife wildlife {
        get {
            return this.wildlifeField;
        }
        set {
            this.wildlifeField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWork_live_study work_live_study {
        get {
            return this.work_live_studyField;
        }
        set {
            this.work_live_studyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint atlas_id {
        get {
            return this.atlas_idField;
        }
        set {
            this.atlas_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string asset_id {
        get {
            return this.asset_idField;
        }
        set {
            this.asset_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("title-ascii")]
    public string titleascii {
        get {
            return this.titleasciiField;
        }
        set {
            this.titleasciiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationHistory {
    
    private destinationsDestinationHistoryHistory historyField;
    
    /// <remarks/>
    public destinationsDestinationHistoryHistory history {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationHistoryHistory {
    
    private string[] historyField;
    
    private string overviewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("history")]
    public string[] history {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationIntroductory {
    
    private destinationsDestinationIntroductoryIntroduction introductionField;
    
    /// <remarks/>
    public destinationsDestinationIntroductoryIntroduction introduction {
        get {
            return this.introductionField;
        }
        set {
            this.introductionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationIntroductoryIntroduction {
    
    private string overviewField;
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationPractical_information {
    
    private destinationsDestinationPractical_informationHealth_and_safety health_and_safetyField;
    
    private destinationsDestinationPractical_informationMoney_and_costs money_and_costsField;
    
    private destinationsDestinationPractical_informationVisas visasField;
    
    /// <remarks/>
    public destinationsDestinationPractical_informationHealth_and_safety health_and_safety {
        get {
            return this.health_and_safetyField;
        }
        set {
            this.health_and_safetyField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationPractical_informationMoney_and_costs money_and_costs {
        get {
            return this.money_and_costsField;
        }
        set {
            this.money_and_costsField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationPractical_informationVisas visas {
        get {
            return this.visasField;
        }
        set {
            this.visasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationPractical_informationHealth_and_safety {
    
    private string[] before_you_goField;
    
    private string[] dangers_and_annoyancesField;
    
    private string[] in_transitField;
    
    private string[] while_youre_thereField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("before_you_go")]
    public string[] before_you_go {
        get {
            return this.before_you_goField;
        }
        set {
            this.before_you_goField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dangers_and_annoyances")]
    public string[] dangers_and_annoyances {
        get {
            return this.dangers_and_annoyancesField;
        }
        set {
            this.dangers_and_annoyancesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("in_transit")]
    public string[] in_transit {
        get {
            return this.in_transitField;
        }
        set {
            this.in_transitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("while_youre_there")]
    public string[] while_youre_there {
        get {
            return this.while_youre_thereField;
        }
        set {
            this.while_youre_thereField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationPractical_informationMoney_and_costs {
    
    private string costsField;
    
    private string[] moneyField;
    
    /// <remarks/>
    public string costs {
        get {
            return this.costsField;
        }
        set {
            this.costsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("money")]
    public string[] money {
        get {
            return this.moneyField;
        }
        set {
            this.moneyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationPractical_informationVisas {
    
    private string[] otherField;
    
    private string permitsField;
    
    private string overviewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("other")]
    public string[] other {
        get {
            return this.otherField;
        }
        set {
            this.otherField = value;
        }
    }
    
    /// <remarks/>
    public string permits {
        get {
            return this.permitsField;
        }
        set {
            this.permitsField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationTransport {
    
    private destinationsDestinationTransportGetting_there_and_around getting_there_and_aroundField;
    
    private destinationsDestinationTransportGetting_around getting_aroundField;
    
    private destinationsDestinationTransportGetting_there_and_away getting_there_and_awayField;
    
    /// <remarks/>
    public destinationsDestinationTransportGetting_there_and_around getting_there_and_around {
        get {
            return this.getting_there_and_aroundField;
        }
        set {
            this.getting_there_and_aroundField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationTransportGetting_around getting_around {
        get {
            return this.getting_aroundField;
        }
        set {
            this.getting_aroundField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationTransportGetting_there_and_away getting_there_and_away {
        get {
            return this.getting_there_and_awayField;
        }
        set {
            this.getting_there_and_awayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationTransportGetting_there_and_around {
    
    private string[] airField;
    
    private string bicycleField;
    
    private string bus_and_tramField;
    
    private string[] car_and_motorcycleField;
    
    private string[] local_transportField;
    
    private string overviewField;
    
    private string trainField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("air")]
    public string[] air {
        get {
            return this.airField;
        }
        set {
            this.airField = value;
        }
    }
    
    /// <remarks/>
    public string bicycle {
        get {
            return this.bicycleField;
        }
        set {
            this.bicycleField = value;
        }
    }
    
    /// <remarks/>
    public string bus_and_tram {
        get {
            return this.bus_and_tramField;
        }
        set {
            this.bus_and_tramField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("car_and_motorcycle")]
    public string[] car_and_motorcycle {
        get {
            return this.car_and_motorcycleField;
        }
        set {
            this.car_and_motorcycleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("local_transport")]
    public string[] local_transport {
        get {
            return this.local_transportField;
        }
        set {
            this.local_transportField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
    
    /// <remarks/>
    public string train {
        get {
            return this.trainField;
        }
        set {
            this.trainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationTransportGetting_around {
    
    private string[] airField;
    
    private string[] bus_and_tramField;
    
    private string bicycleField;
    
    private string boatField;
    
    private string[] car_and_motorcycleField;
    
    private string hitchingField;
    
    private string[] local_transportField;
    
    private string overviewField;
    
    private string trainField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("air")]
    public string[] air {
        get {
            return this.airField;
        }
        set {
            this.airField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bus_and_tram")]
    public string[] bus_and_tram {
        get {
            return this.bus_and_tramField;
        }
        set {
            this.bus_and_tramField = value;
        }
    }
    
    /// <remarks/>
    public string bicycle {
        get {
            return this.bicycleField;
        }
        set {
            this.bicycleField = value;
        }
    }
    
    /// <remarks/>
    public string boat {
        get {
            return this.boatField;
        }
        set {
            this.boatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("car_and_motorcycle")]
    public string[] car_and_motorcycle {
        get {
            return this.car_and_motorcycleField;
        }
        set {
            this.car_and_motorcycleField = value;
        }
    }
    
    /// <remarks/>
    public string hitching {
        get {
            return this.hitchingField;
        }
        set {
            this.hitchingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("local_transport")]
    public string[] local_transport {
        get {
            return this.local_transportField;
        }
        set {
            this.local_transportField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
    
    /// <remarks/>
    public string train {
        get {
            return this.trainField;
        }
        set {
            this.trainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationTransportGetting_there_and_away {
    
    private string[] airField;
    
    private string[] bus_and_tramField;
    
    private string[] landField;
    
    private string overviewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("air")]
    public string[] air {
        get {
            return this.airField;
        }
        set {
            this.airField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bus_and_tram")]
    public string[] bus_and_tram {
        get {
            return this.bus_and_tramField;
        }
        set {
            this.bus_and_tramField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("land")]
    public string[] land {
        get {
            return this.landField;
        }
        set {
            this.landField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWeather {
    
    private destinationsDestinationWeatherWhen_to_go when_to_goField;
    
    /// <remarks/>
    public destinationsDestinationWeatherWhen_to_go when_to_go {
        get {
            return this.when_to_goField;
        }
        set {
            this.when_to_goField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWeatherWhen_to_go {
    
    private string[] climateField;
    
    private string overviewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("climate")]
    public string[] climate {
        get {
            return this.climateField;
        }
        set {
            this.climateField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWildlife {
    
    private destinationsDestinationWildlifeAnimals animalsField;
    
    private destinationsDestinationWildlifeBirds birdsField;
    
    private destinationsDestinationWildlifeEndangered_species endangered_speciesField;
    
    private destinationsDestinationWildlifeOverview overviewField;
    
    private destinationsDestinationWildlifePlants plantsField;
    
    /// <remarks/>
    public destinationsDestinationWildlifeAnimals animals {
        get {
            return this.animalsField;
        }
        set {
            this.animalsField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWildlifeBirds birds {
        get {
            return this.birdsField;
        }
        set {
            this.birdsField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWildlifeEndangered_species endangered_species {
        get {
            return this.endangered_speciesField;
        }
        set {
            this.endangered_speciesField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWildlifeOverview overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
    
    /// <remarks/>
    public destinationsDestinationWildlifePlants plants {
        get {
            return this.plantsField;
        }
        set {
            this.plantsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWildlifeAnimals {
    
    private string mammalsField;
    
    /// <remarks/>
    public string mammals {
        get {
            return this.mammalsField;
        }
        set {
            this.mammalsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWildlifeBirds {
    
    private string overviewField;
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWildlifeEndangered_species {
    
    private string overviewField;
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWildlifeOverview {
    
    private string overviewField;
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWildlifePlants {
    
    private string overviewField;
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWork_live_study {
    
    private destinationsDestinationWork_live_studyWork workField;
    
    /// <remarks/>
    public destinationsDestinationWork_live_studyWork work {
        get {
            return this.workField;
        }
        set {
            this.workField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class destinationsDestinationWork_live_studyWork {
    
    private string businessField;
    
    private string overviewField;
    
    /// <remarks/>
    public string business {
        get {
            return this.businessField;
        }
        set {
            this.businessField = value;
        }
    }
    
    /// <remarks/>
    public string overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
}
